### ISSUE TITLE
down / up -> deflate / inflate

### ISSUE THREAD

**Issue by ceymard** [teq/serialazy#3]
Hello,

I just stumbled on this library. Haven't used it (yet !), but something striked me immediately : for the sake of consistency, shouldn't down/up in the custom serializers be named deflate / inflate instead ?

I have been a user of cerialize for quite some time now, but I must say I'm not a big fan of it and am looking for a replacement -- this could be it.

Thank you for your work !

**Comment by teq** [comment]
Hi!

Naming is a matter of preference and these functions could be named the same, but I decided to go with `up`/`down` because:

- to avoid confusion between type serializer (`up`/`down`) and facade functions (`deflate`/`inflate`). E.g., when `deflate` is called it not only calls `down` on each property type serializer, but executes validation, name mapping, etc

- `inflate`/`deflate` can be used inside of `up`/`down`:
```typescript
@Serialize({ down: (val: Node) => deflate(val), up: (val: JsonMap) => inflate(Node, val) })
public child: Node;
```

- `up`/`down` is shorter and looks much more compact on fat classes with lots of properties :-)

**Comment by ceymard** [comment]
I have to say I wasn't surprised with the up/down naming since it's pretty common in sql migrations across different tools/framework, but I think it can be a  little confusing for some.

I don't have a better proposal either. The reasons you mention are pretty sound, this can be closed I guess.
